- build.gradle
- src/main/java/com/fisa/woorionebank/common/BaseEntity.java
- src/main/java/com/fisa/woorionebank/common/execption/CustomException.java
- src/main/java/com/fisa/woorionebank/common/execption/EnumModel.java
- src/main/java/com/fisa/woorionebank/common/execption/ErrorCode.java
- src/main/java/com/fisa/woorionebank/common/execption/ErrorResponse.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/AreaDTO.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/Area.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/Concert.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertHistory.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/Status.java
- src/main/java/com/fisa/woorionebank/concert/entity/Area.java
- src/main/java/com/fisa/woorionebank/config/CorsConfig.java
- src/main/java/com/fisa/woorionebank/config/ObjectMapperConfig.java
- src/main/java/com/fisa/woorionebank/config/QueryDslConfig.java
- src/main/java/com/fisa/woorionebank/config/WebConfig.java
- src/main/java/com/fisa/woorionebank/config/WebSecurityConfig.java
- src/main/java/com/fisa/woorionebank/member/controller/MemberController.java
- src/main/java/com/fisa/woorionebank/member/domain/dto/MemberDTO.java
- src/main/java/com/fisa/woorionebank/member/domain/dto/ResponseDTO.java
- src/main/java/com/fisa/woorionebank/member/entity/Member.java
- src/main/java/com/fisa/woorionebank/member/repository/MemberRepository.java
- src/main/java/com/fisa/woorionebank/member/service/MemberService.java
- src/main/java/com/fisa/woorionebank/security/JwtAuthenticationFilter.java
- src/main/java/com/fisa/woorionebank/security/TokenProvider.java
> [FEAT] spring security 적용 (#8)

- build.gradle
- src/main/java/com/fisa/woorionebank/common/BaseEntity.java
- src/main/java/com/fisa/woorionebank/common/execption/CustomException.java
- src/main/java/com/fisa/woorionebank/common/execption/EnumModel.java
- src/main/java/com/fisa/woorionebank/common/execption/ErrorCode.java
- src/main/java/com/fisa/woorionebank/common/execption/ErrorResponse.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/AreaDTO.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/Area.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/Concert.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertHistory.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/Status.java
- src/main/java/com/fisa/woorionebank/concert/entity/Area.java
- src/main/java/com/fisa/woorionebank/config/CorsConfig.java
- src/main/java/com/fisa/woorionebank/config/ObjectMapperConfig.java
- src/main/java/com/fisa/woorionebank/config/QueryDslConfig.java
- src/main/java/com/fisa/woorionebank/config/WebConfig.java
- src/main/java/com/fisa/woorionebank/config/WebSecurityConfig.java
- src/main/java/com/fisa/woorionebank/member/controller/MemberController.java
- src/main/java/com/fisa/woorionebank/member/domain/dto/MemberDTO.java
- src/main/java/com/fisa/woorionebank/member/domain/dto/ResponseDTO.java
- src/main/java/com/fisa/woorionebank/member/entity/Member.java
- src/main/java/com/fisa/woorionebank/member/repository/MemberRepository.java
- src/main/java/com/fisa/woorionebank/member/service/MemberService.java
- src/main/java/com/fisa/woorionebank/security/JwtAuthenticationFilter.java
- src/main/java/com/fisa/woorionebank/security/TokenProvider.java
> [MERGE] 브랜치 병합

- src/main/java/com/fisa/woorionebank/member/controller/MemberController.java
- src/main/java/com/fisa/woorionebank/member/service/MemberService.java
회원가입, 로그인, 로그아웃, 아이디 유효성 검사 기능을 Spring Security를 적용하여 개발했습니다.
Resolves: #11 
어떤 변경 사항이 있나요?
> [FIX] Spring Security 기능 구현 (#11)

- src/main/java/com/fisa/woorionebank/account/entity/Account.java
- src/main/java/com/fisa/woorionebank/account/repository/AccountRepository.java
- src/main/java/com/fisa/woorionebank/account/repository/AccountRepositoryCustom.java
- src/main/java/com/fisa/woorionebank/account/repository/AccountRepositoryImpl.java
- src/main/java/com/fisa/woorionebank/common/dto/ResponseDTO.java
- src/main/java/com/fisa/woorionebank/common/execption/ErrorCode.java
- src/main/java/com/fisa/woorionebank/member/domain/dto/MemberDTO.java
- src/main/java/com/fisa/woorionebank/member/entity/Member.java
- src/main/java/com/fisa/woorionebank/member/repository/MemberRepository.java
- src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
- src/main/java/com/fisa/woorionebank/saving/domain/entity/Celebrity.java
- src/main/java/com/fisa/woorionebank/saving/domain/entity/DepositDay.java
- src/main/java/com/fisa/woorionebank/saving/domain/entity/Saving.java
- src/main/java/com/fisa/woorionebank/saving/domain/entity/SavingRule.java
- src/main/java/com/fisa/woorionebank/saving/domain/requestdto/SavingCreateRequestDTO.java
- src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingDTO.java
- src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingRuleDTO.java
- src/main/java/com/fisa/woorionebank/saving/repository/SavingRepository.java
- src/main/java/com/fisa/woorionebank/saving/repository/SavingRepositoryCustom.java
- src/main/java/com/fisa/woorionebank/saving/repository/SavingRepositoryImpl.java
- src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
- src/main/java/com/fisa/woorionebank/savinghistory/entity/SavingHistory.java
- src/main/java/com/fisa/woorionebank/savinghistory/entity/TransactionType.java
최애적금 로직을 위한 MVC 구조 생성
#13 
어떤 변경 사항이 있나요?
> feat: 기능 새롭게 개발(#13)

- src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/ConcertDTO.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/RequestDrawDTO.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/ResponseConcertDTO.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/Concert.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertHistory.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertVenue.java
- src/main/java/com/fisa/woorionebank/concert/repository/jpa/ConcertHistoryRepository.java
- src/main/java/com/fisa/woorionebank/concert/repository/jpa/ConcertRepository.java
- src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
- src/main/java/com/fisa/woorionebank/seat/domain/dto/RequestSeatDTO.java
- src/main/java/com/fisa/woorionebank/seat/domain/dto/ResponseSeatDTO.java
- src/main/java/com/fisa/woorionebank/seat/entity/Seat.java
- src/main/java/com/fisa/woorionebank/seat/entity/SeatClass.java
- src/main/java/com/fisa/woorionebank/seat/repository/SeatRepository.java
🎉 우리 원 더 스테이지 예매 정보 조회(티켓팅 기간)
💺 우리 원 더 스테이지 예매 좌석 조회(티켓팅 기간)
😎 우리 원 더 스테이지 좌석 예매(티켓팅 기간)
어떤 변경 사항이 있나요?
> [FEAT] 공연 예매 관련 기능 개발(#22)

- src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
- src/main/java/com/fisa/woorionebank/saving/domain/entity/SavingRule.java
- src/main/java/com/fisa/woorionebank/saving/domain/requestdto/SavingAddRuleRequestDTO.java
- src/main/java/com/fisa/woorionebank/saving/domain/requestdto/SavingCreateRequestDTO.java
- src/main/java/com/fisa/woorionebank/saving/domain/responsedto/RuleListDTO.java
- src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingListDTO.java
- src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingRuleDTO.java
- src/main/java/com/fisa/woorionebank/saving/repository/rule/SavingRuleRepository.java
- src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepository.java
- src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepositoryCustom.java
- src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
- src/test/java/com/fisa/woorionebank/service/SavingServiceTest.java
최애 적금에 규칙을 생성하는 기능을 구현하였습니다.
해당 최애적금에 해당되는 규칙 리스트를  조회하는 기능을 구현하였습니다.
#25 
어떤 변경 사항이 있나요?
> 25 feat 최애적금규칙 생성 및 조회

- src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertHistory.java
- src/main/java/com/fisa/woorionebank/concert/repository/jpa/ConcertHistoryRepository.java
- src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
- src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepository.java
🍔 이미 공연을 응모한 멤버 처리
🍔 공연 당첨 A석, B석 당첨 로직
🍔 공연 당첨 조회 API
어떤 변경 사항이 있나요?
> [FEAT] 공연 응모 비즈니스 로직(#14)

- src/main/java/com/fisa/woorionebank/account/service/AccountService.java
- src/main/java/com/fisa/woorionebank/member/entity/Member.java
- src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
- src/main/java/com/fisa/woorionebank/saving/domain/entity/Saving.java
- src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
고객이 가입한 최애적금 리스트를 조회하는 기능을 개발하였습니다
#27 
어떤 변경 사항이 있나요?
> feat: 최애적금 조회 기능 구현(#27)

- src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
- src/main/java/com/fisa/woorionebank/saving/domain/entity/SavingRule.java
- src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingHistoryDTO.java
- src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingHistoryListDTO.java
- src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
- src/main/java/com/fisa/woorionebank/savinghistory/repository/SavingHistoryRepository.java
최애적금 입금 내역을 조회하는 기능을 구현
#32 
어떤 변경 사항이 있나요?
> 최애적금 입금내역 조회

- src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
- src/main/java/com/fisa/woorionebank/concert/repository/jpa/ConcertHistoryRepository.java
- src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
- src/main/java/com/fisa/woorionebank/seat/domain/dto/ResponseSeatDTO.java
🍰 좌석 조회 시 이미 예매가 완료된 좌석(선택 불가), 예매가 가능한 좌석 나누기
🍰 좌석 예매 시 이미 선택된 좌석입니다. 기능 구현
🍰 응모 당첨 로직 수정
어떤 변경 사항이 있나요?
> [FIX] 이미 선택된 좌석입니다(#35)

- src/main/java/com/fisa/woorionebank/concert/domain/dto/ConcertDTO.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/Concert.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertVenue.java
- src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
- src/test/java/com/fisa/woorionebank/service/ControllerServiceTest.java
> [FIX] Concert 테스트 코드(#37)

- src/main/java/com/fisa/woorionebank/account/entity/Account.java
- src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
- src/main/java/com/fisa/woorionebank/saving/domain/entity/Saving.java
- src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepository.java
- src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepositoryCustom.java
- src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepositoryImpl.java
- src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
- src/main/java/com/fisa/woorionebank/saving/service/WeeklyDepositService.java
적금 자동이체 로직을 구현중이었습니다
#34
어떤 변경 사항이 있나요?
> feat: 서비스분리 (#34)

- src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepositoryImpl.java
- src/main/java/com/fisa/woorionebank/saving/service/WeeklyDepositService.java
적금 자동이체 메소드를 구현하였습니다.
자동 이체시 적금 입금내역이 생성되도록 하였습니다.
#40 
어떤 변경 사항이 있나요?
> feat: 적금 자동이체 기능 구현(#40)

- src/main/java/com/fisa/woorionebank/common/execption/ErrorCode.java
- src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
- src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingInfoDTO.java
- src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
최애적금을 상세를 조회하는 기능을 추가했습니다.
#42 
어떤 변경 사항이 있나요?
> 42 feat 적금상세조회

- src/main/java/com/fisa/woorionebank/common/execption/ErrorCode.java
- src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/ConcertHistoryDTO.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/ResponseConcertDTO.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/Concert.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertHistory.java
- src/main/java/com/fisa/woorionebank/concert/domain/entity/ConcertVenue.java
- src/main/java/com/fisa/woorionebank/concert/repository/jpa/ConcertRepository.java
- src/main/java/com/fisa/woorionebank/concert/service/ConcertDrawService.java
- src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
- src/main/java/com/fisa/woorionebank/concert/util/ConcertUtils.java
- src/main/java/com/fisa/woorionebank/seat/repository/SeatRepository.java
- src/test/java/com/fisa/woorionebank/service/ControllerServiceTest.java
- fromEntity, of 추가
- ErrorCode 추가
- 반환 타입 변경
어떤 변경 사항이 있나요?
> refactor: 공연 도메인 리팩토링(#43)

- src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/ConcertHistoryListDTO.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/ReserveAvailableDTO.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/WinnersCountDTO.java
- src/main/java/com/fisa/woorionebank/concert/service/ConcertDrawService.java
- src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
- src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepository.java
- src/main/java/com/fisa/woorionebank/seat/domain/dto/ResponseSeatDTO.java
- src/main/java/com/fisa/woorionebank/seat/domain/dto/SeatListDTO.java
- src/test/java/com/fisa/woorionebank/service/ConcertServiceTest.java
🦈 공연 응모 리팩토링
🦈 공연 예매 가능한 회원인지 확인
🦈 적금 가입자 조회 수정
어떤 변경 사항이 있나요?
> [REFACTOR] Concert 리팩토링(#43)

- src/main/java/com/fisa/woorionebank/account/entity/Account.java
- src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
- src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
- src/main/java/com/fisa/woorionebank/saving/util/AccountNumberGenerator.java
- src/test/java/com/fisa/woorionebank/service/SavingServiceTest.java
> 46 refactor 최애적금 리팩토링

- src/main/java/com/fisa/woorionebank/common/execption/ErrorCode.java
- src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/ConcertReserveDTO.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/ResponseConcertDTO.java
- src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
우리 원 더 스테이지 좌석 예매 결과 조회
- /reservation/info
- searchReserve
어떤 변경 사항이 있나요?
> [FEAT] 우리 원 더 스테이지 좌석 예매 결과 조회(#43)

- src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
- ConcertController
어떤 변경 사항이 있나요?
> feat: Concert Swagger 설명 추가(#43)

- src/main/java/com/fisa/woorionebank/saving/domain/responsedto/RuleListDTO.java
- src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingHistoryListDTO.java
- src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingInfoDTO.java
- src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingListDTO.java
- src/main/java/com/fisa/woorionebank/saving/domain/responsedto/SavingRuleDTO.java
- src/main/java/com/fisa/woorionebank/saving/repository/rule/SavingRuleRepository.java
- src/main/java/com/fisa/woorionebank/saving/repository/rule/SavingRuleRepositoryCustom.java
- src/main/java/com/fisa/woorionebank/saving/repository/rule/SavingRuleRepositoryImpl.java
- src/main/java/com/fisa/woorionebank/saving/repository/saving/SavingRepositoryCustom.java
- src/main/java/com/fisa/woorionebank/saving/service/SavingService.java
- src/test/java/com/fisa/woorionebank/service/SavingServiceTest.java
SavingServiceTest 구현
Saving 관련 테스트를 진행하였습니다.
#52 
어떤 변경 사항이 있나요?
> test: 최애적금 로직 테스트

- src/main/java/com/fisa/woorionebank/common/execption/ErrorCode.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/response/ResponseConcertDTO.java
- src/main/java/com/fisa/woorionebank/concert/domain/dto/response/ResponseDrawDTO.java
- src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
🦁 공연 조회에서 concertVenue 추가
🦁 공연 당첨 조회에서 에러 처리 대신 status 반환으로 수정
어떤 변경 사항이 있나요?
> [FIX] 66 fix concert

- build.gradle
- src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
- src/main/java/com/fisa/woorionebank/concert/repository/jpa/ConcertHistoryRepository.java
- src/main/java/com/fisa/woorionebank/concert/service/ConcertService.java
- src/main/java/com/fisa/woorionebank/config/redisson/AopForTransaction.java
- src/main/java/com/fisa/woorionebank/config/redisson/CustomSpringELParser.java
- src/main/java/com/fisa/woorionebank/config/redisson/DistributedLock.java
- src/main/java/com/fisa/woorionebank/config/redisson/DistributedLockAop.java
- src/main/java/com/fisa/woorionebank/config/redisson/RedissonConfig.java
- src/main/java/com/fisa/woorionebank/saving/controller/SavingController.java
- src/main/java/com/fisa/woorionebank/seat/repository/SeatRepository.java
- src/main/resources/logback-spring.xml
- src/test/java/com/fisa/woorionebank/dumy/Dummy.java
- src/test/java/com/fisa/woorionebank/service/ConcertServiceTest.java
- src/test/java/com/fisa/woorionebank/service/DistributedLockTest.java
레디스 redisson을 활용한 분산락 구현
#69 
어떤 변경 사항이 있나요?
> 69 feat 분산락 구현

- src/main/java/com/fisa/woorionebank/concert/controller/ConcertController.java
> fix: get mapping
